/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface':                '#071e27',
        'on-primary-container':      '#fdfcff',
        'secondary-fixed-dim':       '#a7c8ff',
        'surface-bright':            '#f3faff',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'primary-container':         '#167aba',
        'primary':                   '#006097',
        'primary-fixed':             '#cee5ff',
        'primary-fixed-dim':         '#96ccff',
        'on-primary':                '#ffffff',
        'on-primary-fixed':          '#001d32',
        'on-primary-fixed-variant':  '#004a76',
        'secondary':                 '#325f9b',
        'secondary-container':       '#93bdff',
        'secondary-fixed':           '#d5e3ff',
        'on-secondary':              '#ffffff',
        'on-secondary-fixed':        '#001c3b',
        'on-secondary-container':    '#194b86',
        'tertiary':                  '#006671',
        'tertiary-container':        '#00818f',
        'tertiary-fixed':            '#98f0ff',
        'on-tertiary':               '#ffffff',
        'on-tertiary-fixed':         '#001f24',
        'surface':                   '#f3faff',
        'surface-dim':               '#c7dde9',
        'surface-variant':           '#cfe6f2',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#e6f6ff',
        'surface-container':         '#dbf1fe',
        'surface-container-high':    '#d5ecf8',
        'surface-container-highest': '#cfe6f2',
        'outline':                   '#707881',
        'outline-variant':           '#c0c7d1',
        'inverse-surface':           '#1e333c',
        'inverse-primary':           '#96ccff',
        'on-surface-variant':        '#404750',
        'background':                '#f3faff',
        'on-background':             '#071e27',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
